version: '3'

networks:
    nginx-php74-mysql8:

services:
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - mysql8-service
        networks:
            - nginx-php74-mysql8

    php74-service:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php74-container
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/project
        networks:
            - nginx-php74-mysql8

    mysql8-service:
        image: mysql:8.0.26
        container_name: mysql8-container
        ports:
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
        networks:
            - nginx-php74-mysql8